import type {
  BugReport,
  CaseStudy,
  JourneyStep,
  SkillTag,
  TestCase,
  TestRun,
} from "./types";

export const caseStudies: CaseStudy[] = [
  {
    id: "checkout",
    title: "E-commerce Checkout",
    platform: "Web",
    version: "v1.3",
    status: "In Progress",
    signal: "green",
  },
  {
    id: "registration",
    title: "User Registration Flow",
    platform: "Web",
    version: "v1.0",
    status: "Draft",
    signal: "gray",
  },
  {
    id: "gateway",
    title: "Payment Gateway",
    platform: "Web",
    version: "v1.2",
    status: "In Progress",
    signal: "green",
  },
  {
    id: "mobile-login",
    title: "Mobile App Login",
    platform: "iOS",
    version: "v1.1",
    status: "Draft",
    signal: "gray",
  },
  {
    id: "search",
    title: "Search & Filters",
    platform: "Web",
    version: "v1.0",
    status: "Ready",
    signal: "green",
  },
];

export const skillTags: SkillTag[] = [
  { label: "Test Design", count: 14 },
  { label: "UI Testing", count: 9 },
  { label: "API Testing", count: 7 },
  { label: "E2E Testing", count: 6 },
  { label: "Accessibility", count: 5 },
  { label: "Performance", count: 4 },
  { label: "Security", count: 4 },
  { label: "Cross Browser", count: 6 },
  { label: "AI Automation", count: 5 },
  { label: "Bug Analysis", count: 8 },
];

export const journeySteps: JourneyStep[] = [
  { id: "cart", label: "Cart", status: "done" },
  { id: "information", label: "Information", status: "done" },
  { id: "shipping", label: "Shipping", status: "done" },
  { id: "payment", label: "Payment", status: "current" },
  { id: "review", label: "Review", status: "queued" },
  { id: "confirmation", label: "Confirmation", status: "queued" },
];

export const testCases: TestCase[] = [
  {
    id: "TC-042",
    title: "Complete purchase with valid card",
    type: "E2E",
    priority: "P0",
    status: "Passed",
    stage: "Confirmation",
    owner: "Denis",
    lastRun: "Jul 21, 10:15",
  },
  {
    id: "TC-041",
    title: "Declined card shows error message",
    type: "E2E",
    priority: "P0",
    status: "Failed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 10:15",
  },
  {
    id: "TC-040",
    title: "CVV validation on blur",
    type: "Functional",
    priority: "P1",
    status: "Passed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 09:58",
  },
  {
    id: "TC-039",
    title: "Empty card number validation",
    type: "Functional",
    priority: "P1",
    status: "Passed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 09:58",
  },
  {
    id: "TC-038",
    title: "Expiration date in the past",
    type: "Functional",
    priority: "P1",
    status: "Failed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 09:45",
  },
  {
    id: "TC-037",
    title: "Place order with PayPal",
    type: "E2E",
    priority: "P2",
    status: "Passed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 09:30",
  },
  {
    id: "TC-036",
    title: "Loading state on place order",
    type: "UI",
    priority: "P2",
    status: "Blocked",
    stage: "Review",
    owner: "Denis",
    lastRun: "Jul 21, 09:10",
  },
  {
    id: "TC-035",
    title: "Order review summary is correct",
    type: "Functional",
    priority: "P2",
    status: "Not Run",
    stage: "Review",
    owner: "Denis",
    lastRun: "-",
  },
  {
    id: "TC-034",
    title: "Back to cart from payment",
    type: "E2E",
    priority: "P3",
    status: "Passed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 08:50",
  },
  {
    id: "TC-033",
    title: "Guest checkout flow",
    type: "E2E",
    priority: "P3",
    status: "Not Run",
    stage: "Information",
    owner: "Denis",
    lastRun: "-",
  },
  {
    id: "TC-032",
    title: "Payment form labels are accessible",
    type: "Accessibility",
    priority: "P1",
    status: "Passed",
    stage: "Payment",
    owner: "Denis",
    lastRun: "Jul 21, 08:41",
  },
  {
    id: "TC-031",
    title: "Checkout summary loads under 2 seconds",
    type: "Performance",
    priority: "P2",
    status: "Not Run",
    stage: "Review",
    owner: "Denis",
    lastRun: "-",
  },
];

export const bugReport: BugReport = {
  id: "BUG-016",
  title: "Error message not shown for declined card on Payment step",
  severity: "Major",
  priority: "P0",
  type: "Functional",
  reportedBy: "Denis Dacenko",
  reportedOn: "Jul 21, 2026 10:18",
  environment: "Chrome 126 / macOS 15",
  linkedTestCaseId: "TC-041",
  steps: [
    "Go to Checkout > Payment step",
    "Enter card number 4000 0000 0000 0002",
    "Enter any future expiry date",
    "Enter any valid CVV",
    "Click Place Order",
    "Observe the payment form",
  ],
  expected:
    "An error message should be displayed: Your card was declined. Please try a different card.",
  actual:
    "No error message is shown. The button returns to enabled state and the user is not informed about the payment failure.",
  evidence: [
    {
      label: "Screenshot_2026-07-21_10-18.png",
      meta: "1440x1000, 320 KB",
      kind: "screenshot",
    },
    {
      label: "Console log",
      meta: "3 errors, 2 warnings",
      kind: "log",
    },
  ],
};

export const testRuns: TestRun[] = [
  {
    id: "Run #28",
    name: "Smoke",
    startedAt: "Jul 21, 10:15",
    scope: "Checkout",
    passed: 7,
    failed: 2,
    blocked: 1,
    total: 12,
  },
  {
    id: "Run #27",
    name: "Regression",
    startedAt: "Jul 20, 18:40",
    scope: "Payment",
    passed: 6,
    failed: 3,
    blocked: 1,
    total: 12,
  },
  {
    id: "Run #26",
    name: "Payment",
    startedAt: "Jul 20, 16:22",
    scope: "Risk-based",
    passed: 4,
    failed: 1,
    blocked: 1,
    total: 12,
  },
];
